### ISSUE TITLE
Can no longer run locally

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#122]
`activator run` yields

```
--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

[warn] Credentials file /Users/martijnv/.ivy2/.credentials does not exist
[info] JavaScript linting on 2 source(s)
[error] undefined:23
[error]     // Libraries
[error]     ^
[error]
[error] SyntaxError: Unexpected token / in JSON at position 373
[error]     at Object.parse (native)
[error]     at /Users/martijnv/dev/maproulette2-myfork/target/jshint/jshint-shell.js:29:24
[error]     at Object.<anonymous> (/Users/martijnv/dev/maproulette2-myfork/target/jshint/jshint-shell.js:66:2)
[error]     at Module._compile (module.js:541:32)
[error]     at Object.Module._extensions..js (module.js:550:10)
[error]     at Module.load (module.js:458:32)
[error]     at tryModuleLoad (module.js:417:12)
[error]     at Function.Module._load (module.js:409:3)
[error]     at Function.Module.runMain (module.js:575:10)
[error]     at startup (node.js:160:18)
[error] undefined:23
[error]     // Libraries
[error]     ^
[error]
...
```

**Comment by mgcuthbert** [comment]
delete your target directory under "maproulette2-myfork", and then try again. I have a suspicion that something is hiding there. You might be able to do sbt clean first as well and then run.

**Comment by mvexel** [comment]
should have mentioned, tried that (removing `/target` as well as `project/project` and `project/target` but error persists. I sense that it has to do with `sbt-less` or `sbt-jshint`. I thought it might be related to this bug in an older version of `sbt-jshint` so next I tried to update `plugins.sbt` to current version 1.0.4 of sbt-jshint, which produced a whole different class of errors to do with the the JS hinting itself:

```
[info] JavaScript linting on 2 source(s)
[error] /Users/martijnv/dev/maproulette2-myfork/app/assets/javascripts/main.js:15: Strings must use singlequote.
[error]     "positionClass": "toast-top-center",
[error]                    ^
[error] /Users/martijnv/dev/maproulette2-myfork/app/assets/javascripts/main.js:15: Strings must use singlequote.
[error]     "positionClass": "toast-top-center",
[error]                                        ^
[error] /Users/martijnv/dev/maproulette2-myfork/app/assets/javascripts/main.js:16: Strings must use singlequote.
[error]     "toastClass": "notification",
[error]                 ^
[error] /Users/martijnv/dev/maproulette2-myfork/app/assets/javascripts/main.js:16: Strings must use singlequote.
[error]     "toastClass": "notification",
[error]                                 ^
[error] /Users/martijnv/dev/maproulette2-myfork/app/assets/javascripts/main.js:17: Strings must use singlequote.
[error]     "closeButton": false,
[error]                  ^
[error] 51 errors found
```

My guess is the default behavior for the jshint plugin was changed between `1.0.1` and `1.0.4` and it's doing much more strict checking than before. That's as far as I got for now.
