### ISSUE TITLE
Running MapRoulette locally fails with JS error

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#207]
After cloning MapRoulette and running with `activator run -Dconfig.resource=~/dev/dev.conf` I get the following error message after a while:

```
[info]
[info]
com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: /Users/martijnv/node_modules/less/lib/less/parser/parser.js:117
            imports.contents[fileInfo.filename] = str;
                   ^

TypeError: Cannot read property 'contents' of undefined
    at Object.parse (/Users/martijnv/node_modules/less/lib/less/parser/parser.js:117:20)
    at /Users/martijnv/dev/maproulette2/target/less/lessc.js:58:20
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)

	at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:195)
	at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:167)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
	at scala.util.Try$.apply(Try.scala:161)
	at scala.util.Success.map(Try.scala:206)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Not sure what's going on here?

**Comment by mgcuthbert** [comment]
This seems to be an issue with the latest version of sbt-less that you updated that contains a bug as described here: https://github.com/sbt/sbt-less/issues/80

Ultimately the solution is to delete the project/project and project/target directories first and then re-run and you should be good to go.

**Comment by mvexel** [comment]
Yea the bug actually appeared before I updated the library and triggered me to do just that.
