### ISSUE TITLE
Completing a challenge in the wizard impossible

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#231]
Gives JS error: 

```javascript
Uncaught TypeError: Cannot read property 'replace' of undefined
    at HTMLDivElement.<anonymous> (http://maproulette.org/ui/admin/form/challenge/1/-1:1581:37)
    at HTMLDivElement.dispatch (http://maproulette.org/webjars/jquery/2.2.4/jquery.js:4737:27)
    at HTMLDivElement.elemData.handle (http://maproulette.org/webjars/jquery/2.2.4/jquery.js:4549:28)
    at Object.trigger (http://maproulette.org/webjars/jquery/2.2.4/jquery.js:7807:12)
    at HTMLDivElement.<anonymous> (http://maproulette.org/webjars/jquery/2.2.4/jquery.js:7875:17)
    at Function.each (http://maproulette.org/webjars/jquery/2.2.4/jquery.js:365:19)
    at jQuery.fn.init.each (http://maproulette.org/webjars/jquery/2.2.4/jquery.js:137:17)
    at jQuery.fn.init.trigger (http://maproulette.org/webjars/jquery/2.2.4/jquery.js:7874:15)
    at c.next (http://maproulette.org/webjars/fuelux/3.14.2/dist/js/fuelux.min.js:7:27097)
    at HTMLButtonElement.proxy (http://maproulette.org/webjars/jquery/2.2.4/jquery.js:497:14)
```

**Comment by mvexel** [comment]
This was fixed in #232
