### ISSUE TITLE
Difficulties installing Play Framework Activator / Install clarification

### ISSUE THREAD

**Issue by rmrice** [maproulette/maproulette2#328]
Hi! Trying to get this installed on Ubuntu 16 (also Centos7, but will focus on Ubuntu first) and having trouble getting the Play Framework activator installed. I am unfamiliar with Play and sbt so bear with me.

The instructions are unclear in the readme how to get activator properly installed, and what specifically is needed. It appears as though I have tried downloading sbt from the download page (latest version), but am not sure how to proceed from the docs on the play website. It also looks like activator via play is getting EOL'ed (https://www.lightbend.com/community/core-tools/activator-and-sbt), so I am not sure this is the correct way to go about installing.

I have also tried installing sbt and typesafe activator this way:

```
curl https://bintray.com/sbt/rpm/rpm > bintray-sbt-rpm.repo
sudo mv bintray-sbt-rpm.repo /etc/yum.repos.d/
sudo yum install sbt
wget https://downloads.typesafe.com/typesafe-activator/1.3.6/typesafe-activator-1.3.6.zip
unzip typesafe-activator-1.3.6.zip
mv activator-dist-1.3.6 /opt
ln -s /opt/activator-dist-1.3.6/activator /usr/local/sbin/activator
export PATH=/usr/local/sbin/activator:$PATH
```

This works, and I have tried different versions of typesafe-activator, but am getting this error in console: 
```
Credentials file /home/centos/.ivy2/.credentials does not exist
```
and

```
[error] p.c.s.n.PlayRequestHandler - Exception caught in Netty
java.lang.NoClassDefFoundError: Could not initialize class play.api.http.DefaultHttpErrorHandler$
    at play.core.server.Server$class.logExceptionAndGetResult$1(Server.scala:45)
    at play.core.server.Server$class.getHandlerFor(Server.scala:65)
    at play.core.server.NettyServer.getHandlerFor(NettyServer.scala:47)
    at play.core.server.netty.PlayRequestHandler.handle(PlayRequestHandler.scala:82)
    at play.core.server.netty.PlayRequestHandler.channelRead(PlayRequestHandler.scala:163)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
    at com.typesafe.netty.http.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:129)
    at com.typesafe.netty.http.HttpStreamsServerHandler.channelRead(HttpStreamsServerHandler.java:96)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
```

Same issue as https://github.com/maproulette/maproulette2/issues/33. I would try downgrading Play, but since I didn't install it directly, and direct downloads of play aren't available past 2.3.0, I have no idea how to uninstall and re-install. I would love a little more guidance / clarification on how to get Play Activator installed properly.

**Comment by rmrice** [comment]
I fixed this by just installing sbt, then in my maproulette directory, run `sbt` and then `run`.

**Comment by mvexel** [comment]
Glad you got it fixed @rmrice ! Let me know if there's any other way I can help.
