### ISSUE TITLE
OAuth Issues hitting OSM Dev Server

### ISSUE THREAD

**Issue by rmrice** [maproulette/maproulette2#330]
Good news, I have the app stood up on ubuntu 16 and it works, and I have set up oauth access via https://master.apis.dev.openstreetmap.org. I exported my environment variables as the readme instructed. MapRoulette starts, but when I try to sign in I get this error in my console:

```

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

[warn] Credentials file /home/ubuntu/.ivy2/.credentials does not exist
Warning: node.js detection failed, sbt will use the Rhino based Trireme JavaScript engine instead to run JavaScript assets compilation, which in some cases may be orders of magnitude slower than using node.js.
[warn] Credentials file /home/ubuntu/.ivy2/.credentials does not exist
DEBUG - Starting application default Akka system: application
INFO  - Creating Pool for datasource 'default'
INFO  - Database [default] connected at jdbc:postgresql://localhost:5432/mp_dev?user=osm&password=osm
INFO  - Cleaning locks every 1 hour
INFO  - Running challenge Schedules every 1 day
INFO  - Updating locations every 12 hours
INFO  - Application started (Dev)
ERROR - Communication with the service provider failed: hostname in certificate didn't match: <master.apis.dev.openstreetmap.org> != <apis.dev.openstreetmap.org> OR <apis.dev.openstreetmap.org>
oauth.signpost.exception.OAuthCommunicationException: Communication with the service provider failed: hostname in certificate didn't match: <master.apis.dev.openstreetmap.org> != <apis.dev.openstreetmap.org> OR <apis.dev.openstreetmap.org>
        at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:218)
        at oauth.signpost.AbstractOAuthProvider.retrieveRequestToken(AbstractOAuthProvider.java:74)
        at play.api.libs.oauth.OAuth.retrieveRequestToken(OAuth.scala:36)
        at org.maproulette.session.SessionManager.retrieveRequestToken(SessionManager.scala:84)
        at controllers.AuthController$$anonfun$authenticate$1$$anonfun$apply$1.apply(AuthController.scala:66)
        at controllers.AuthController$$anonfun$authenticate$1$$anonfun$apply$1.apply(AuthController.scala:39)
        at scala.util.Try$.apply(Try.scala:192)
        at org.maproulette.exception.MPExceptionUtil$.internalAsyncUIExceptionCatcher(MPExceptionUtil.scala:138)
        at controllers.AuthController$$anonfun$authenticate$1.apply(AuthController.scala:39)
        at controllers.AuthController$$anonfun$authenticate$1.apply(AuthController.scala:38)
        at play.api.mvc.Action$.invokeBlock(Action.scala:498)
        at play.api.mvc.Action$.invokeBlock(Action.scala:495)
        at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:458)
        at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
        at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:111)
        at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5.apply(Action.scala:110)
        at scala.Option.map(Option.scala:146)
        at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:110)
        at play.api.mvc.Action$$anonfun$apply$2.apply(Action.scala:103)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:405)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: javax.net.ssl.SSLException: hostname in certificate didn't match: <master.apis.dev.openstreetmap.org> != <apis.dev.openstreetmap.org> OR <apis.dev.openstreetmap.org>
        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:220)
        at org.apache.http.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostnameVerifier.java:54)
        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:149)
        at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:130)
        at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:339)
        at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:123)
        at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:147)
        at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:108)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:641)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:576)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:554)
        at oauth.signpost.commonshttp.CommonsHttpOAuthProvider.sendRequest(CommonsHttpOAuthProvider.java:64)
        at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:181)
        ... 35 common frames omitted
```

I've tried changing the server url to `http://api06.dev.openstreetmap.org` since it appears that redirects to master dev, and get this:

```
ERROR - Communication with the service provider failed: Service provider responded in error: 301 (Moved Permanently)
oauth.signpost.exception.OAuthCommunicationException: Communication with the service provider failed: Service provider responded in error: 301 (Moved Permanently)
```

I tried hitting just `http://apis.dev.openstreetmap.org` and:
```
ERROR - Communication with the service provider failed: Service provider responded in error: 404 (Not Found)
oauth.signpost.exception.OAuthCommunicationException: Communication with the service provider failed: Service provider responded in error: 404 (Not Found)
```

And then without http/s:
```
ERROR - Communication with the service provider failed: java.lang.NullPointerException
oauth.signpost.exception.OAuthCommunicationException: Communication with the service provider failed: java.lang.NullPointerException
```

I have also tried hardcoding my environment variables in application.conf with no luck.

I'm not sure if this is a configuration problem or some other problem, and I'm not well-versed enough in play/scala to debug effectively if it's the latter. Any insight is appreciated!

**Comment by mvexel** [comment]
Hi @rmrice ---

Try switching to `https://api06.dev.openstreetmap.org` instead of `http://api06.dev.openstreetmap.org`

**Comment by rmrice** [comment]
Thanks @mvexel for getting back to me so quick.

I'm still getting this error when I use https://api06.dev.openstreetmap.org:

```
ERROR - Communication with the service provider failed: hostname in certificate didn't match: <api06.dev.openstreetmap.org> != <apis.dev.openstreetmap.org> OR <apis.dev.openstreetmap.org>
oauth.signpost.exception.OAuthCommunicationException: Communication with the service provider failed: hostname in certificate didn't match: <api06.dev.openstreetmap.org> != <apis.dev.openstreetmap.org> OR <apis.dev.openstreetmap.org>
```

**Comment by mvexel** [comment]
Hm. Do you use the `start.sh` script that has the predefined OAuth keys?

**Comment by rmrice** [comment]
No, I exported my own that I generated on the dev server.

**Comment by mvexel** [comment]
Did you generate it at https://api06.dev.openstreetmap.org/user/<username>/oauth_clients/new ?

**Comment by rmrice** [comment]
Yes. Originally I had done it on master.dev.openstreetmap but generated new keys on the api06 address (not sure it matters since it seems like they are both [the same instance](http://wiki.openstreetmap.org/wiki/OAuth#Usage_for_developers)), still same error :confused:

**Comment by mvexel** [comment]
🤔 Perhaps delete and recreate your database or drop the tables?

**Comment by mvexel** [comment]
And / or delete the `target/` and `project/target` and `project/project/target` dirs.

**Comment by treycaldwell** [comment]
I'm looking at this too.  I don't understand why it's comparing the hostname of the certificate presented by master.apis.dev.openstreetmap.org to apis.dev.openstreetmap.org.  I'm unable to find any reference to apis.dev.openstreetmap.org in the source.  Using `curl -vvI https://master.apis.dev.openstreetmap.org` shows that the cert's common name matches the hostname and that the certificate is valid.  There is no redirect as a HTTP 200 is returned.  Any help or ideas is greatly appreciated.

**Comment by treycaldwell** [comment]
Upgrading openjdk to 8u152 fixed this for us (had 8u131).  Thanks to @ianmcorvidae and @mvexel.

**Comment by mvexel** [comment]
@iandees gets the kudos :)

**Comment by rmrice** [comment]
Yep, java version was the culprit. Thanks @mvexel @treycaldwell @ianmcorvidae  :)
