### ISSUE TITLE
maproulette2 setup API_HOST environment variable issue.

### ISSUE THREAD

**Issue by kristenkam** [maproulette/maproulette2#396]
I received the following stacktrace when trying to launch the maproulette2 application:

Where should I update the API_HOST variable? It wasn't clear to me in the instructions.

```
,org.maproulette.session,org.maproulette.actions,org.maproulette.data com.iheart.playSwagger.EnvironmentVariablesTransformer
[error] (run-main-0) java.lang.IllegalStateException: Unable to find variable API_HOST
java.lang.IllegalStateException: Unable to find variable API_HOST
    at com.iheart.playSwagger.PlaceholderVariablesTransformer$$anonfun$apply$1.apply(OutputTransformer.scala:63)
    at com.iheart.playSwagger.PlaceholderVariablesTransformer$$anonfun$apply$1.apply(OutputTransformer.scala:60)
    at com.iheart.playSwagger.OutputTransformer$$anonfun$3.apply(OutputTransformer.scala:44)
    at com.iheart.playSwagger.OutputTransformer$$anonfun$3.apply(OutputTransformer.scala:41)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
    at scala.collection.AbstractTraversable.map(Traversable.scala:104)
    at com.iheart.playSwagger.OutputTransformer$.traverseTransformer(OutputTransformer.scala:41)
    at com.iheart.playSwagger.PlaceholderVariablesTransformer.apply(OutputTransformer.scala:60)
    at com.iheart.playSwagger.PlaceholderVariablesTransformer.apply(OutputTransformer.scala:59)
    at scala.util.Success.flatMap(Try.scala:231)
    at com.iheart.playSwagger.OutputTransformer$$anonfun$$greater$eq$greater$1.apply(OutputTransformer.scala:16)
    at com.iheart.playSwagger.OutputTransformer$$anonfun$$greater$eq$greater$1.apply(OutputTransformer.scala:15)
    at com.iheart.playSwagger.OutputTransformer$SimpleOutputTransformer.apply(OutputTransformer.scala:22)
    at com.iheart.playSwagger.OutputTransformer$SimpleOutputTransformer.apply(OutputTransformer.scala:21)
    at com.iheart.playSwagger.SwaggerSpecGenerator$$anonfun$generateFromRoutesFile$1.apply(SwaggerSpecGenerator.scala:102)
    at com.iheart.playSwagger.SwaggerSpecGenerator$$anonfun$generateFromRoutesFile$1.apply(SwaggerSpecGenerator.scala:98)
    at scala.util.Success.flatMap(Try.scala:231)
    at com.iheart.playSwagger.SwaggerSpecGenerator.generateFromRoutesFile(SwaggerSpecGenerator.scala:98)
    at com.iheart.playSwagger.SwaggerSpecGenerator.generate(SwaggerSpecGenerator.scala:43)
    at com.iheart.playSwagger.SwaggerSpecRunner$.swaggerJson(SwaggerSpecRunner.scala:23)
    at com.iheart.playSwagger.SwaggerSpecRunner$.delayedEndpoint$com$iheart$playSwagger$SwaggerSpecRunner$1(SwaggerSpecRunner.scala:26)
    at com.iheart.playSwagger.SwaggerSpecRunner$delayedInit$body.apply(SwaggerSpecRunner.scala:7)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at com.iheart.playSwagger.SwaggerSpecRunner$.main(SwaggerSpecRunner.scala:7)
    at com.iheart.playSwagger.SwaggerSpecRunner.main(SwaggerSpecRunner.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at sbt.Run.invokeMain(Run.scala:67)
    at sbt.Run.run0(Run.scala:61)
    at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
    at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
    at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
    at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
    at sbt.Logger$$anon$4.apply(Logger.scala:84)
    at sbt.TrapExit$App.run(TrapExit.scala:248)
    at java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: Nonzero exit code: 1
    at scala.sys.package$.error(package.scala:27)
    at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:2128)
    at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:2128)
    at scala.Option.foreach(Option.scala:236)
    at sbt.BuildCommon$class.toError(Defaults.scala:2128)
    at sbt.package$.toError(package.scala:4)
    at com.iheart.sbtPlaySwagger.SwaggerPlugin$$anonfun$projectSettings$9.apply(SwaggerPlugin.scala:41)
    at com.iheart.sbtPlaySwagger.SwaggerPlugin$$anonfun$projectSettings$9.apply(SwaggerPlugin.scala:34)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
[error] (*:swagger) Nonzero exit code: 1
```

**Comment by mgcuthbert** [comment]
You are right this should be made clear in the documentation. For reference it is used for the swagger API documentation that is hosted by the same server. To get past this you would need to make sure there is an environment variable in your path that is basically `API_HOST=<SERVER>` where <SERVER> is the host that you are starting the server on. Eg. localhost:8080.

An example of running it locally using sbt is the following:
`export API_HOST=localhost:8080;sbt run -Dhttp.port=8080 -Dconfig.resource=dev.conf`

**Comment by mgcuthbert** [comment]
I will leave this open so that we address the lack of documentation regarding this.

**Comment by mgcuthbert** [comment]
Readme docs update in PR #410
