### ISSUE TITLE
Code does not compile on encryped FS

### ISSUE THREAD

**Issue by mvexel** [maproulette/maproulette2#418]
when compiling on Linux on an encrypted volume 

```
[error] /home/mvexel/dev/maproulette2/app/org/maproulette/data/DataManager.scala:249: File name too long
[error] This can happen on some encrypted or legacy file systems.  Please see SI-3623 for more details.
[error]         falsePositive <- int("false_positive")
```

**Comment by nrotstan** [comment]
What version of scala are you using?

**Comment by mvexel** [comment]
```
mvexel@x220:~/dev/maproulette2$ scala -version
Scala code runner version 2.11.12 -- Copyright 2002-2017, LAMP/EPFL
```

**Comment by nrotstan** [comment]
Can you try 2.12 or higher and see if that solves the problem? Discussion in scala/scala#5088 suggests that a primary cause of long filenames was addressed in 2.12.

**Comment by mgcuthbert** [comment]
MapRoulette was recently upgraded to the latest version of Scala, specifically 2.12.6. So please try again, hopefully that will resolve it.

**Comment by mvexel** [comment]
Confirming that it does compile now. It does give this error on runtime but it doesn't seem to preclude the application from running otherwise:

```
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
	at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
	at jline.UnixTerminal.<init>(UnixTerminal.java:65)
	at jline.UnixTerminal.<init>(UnixTerminal.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
	at jline.TerminalFactory.create(TerminalFactory.java:102)
	at jline.TerminalFactory.get(TerminalFactory.java:186)
	at jline.TerminalFactory.get(TerminalFactory.java:192)
	at sbt.ConsoleLogger$.ansiSupported(ConsoleLogger.scala:123)
	at sbt.ConsoleLogger$.<init>(ConsoleLogger.scala:117)
	at sbt.ConsoleLogger$.<clinit>(ConsoleLogger.scala)
	at sbt.GlobalLogging$.initial(GlobalLogging.scala:43)
	at sbt.StandardMain$.initialGlobalLogging(Main.scala:116)
	at sbt.StandardMain$.initialState(Main.scala:125)
	at sbt.xMain.run(Main.scala:34)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
	at xsbt.boot.Boot$.main(Boot.scala:18)
	at xsbt.boot.Boot.main(Boot.scala)
```

**Comment by mgcuthbert** [comment]
Closing issue based on last comment by @mvexel.
