### ISSUE TITLE
"No User found using id [-1] to check read access" on attempt to move task to Fixed status

### ISSUE THREAD

**Issue by AntonRutkevich** [maproulette/maproulette2#741]
Request to `PUT task/:id/:status`, eg `PUT /api/v2/task/3742/1?requestReview=true` (move task 3742 to "Fixed" status) produces the following stacktrace:

```
16:27:04.485 [scala-execution-context-global-2191] ERROR o.m.exception.MPExceptionUtil$ - No User found using id [-1] to check read access
org.maproulette.exception.NotFoundException: No User found using id [-1] to check read access
	at org.maproulette.permissions.Permission.hasReadAccess(Permission.scala:67)
	at org.maproulette.models.dal.NotificationDAL.getNotificationSubscriptions(NotificationDAL.scala:207)
	at org.maproulette.models.dal.NotificationDAL.addNotification(NotificationDAL.scala:149)
	at org.maproulette.models.dal.NotificationDAL.createReviewNotification(NotificationDAL.scala:259)
	at org.maproulette.models.dal.TaskDAL.$anonfun$setTaskStatus$5(TaskDAL.scala:677)
	at org.maproulette.models.dal.TaskDAL.$anonfun$setTaskStatus$5$adapted(TaskDAL.scala:609)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at org.maproulette.models.dal.TaskDAL.$anonfun$setTaskStatus$4(TaskDAL.scala:609)
	at org.maproulette.models.utils.TransactionManager.$anonfun$withMRTransaction$1(TransactionManager.scala:29)
	at play.api.db.DefaultDatabase.$anonfun$withTransaction$1(Databases.scala:188)
	at play.api.db.DefaultDatabase.withConnection(Databases.scala:179)
	at play.api.db.DefaultDatabase.withTransaction(Databases.scala:186)
	at org.maproulette.models.utils.TransactionManager.withMRTransaction(TransactionManager.scala:28)
	at org.maproulette.models.utils.TransactionManager.withMRTransaction$(TransactionManager.scala:24)
	at org.maproulette.models.dal.TaskDAL.withMRTransaction(TaskDAL.scala:44)
	at org.maproulette.models.dal.TaskDAL.setTaskStatus(TaskDAL.scala:608)
	at org.maproulette.controllers.api.TaskController.customTaskStatus(TaskController.scala:472)
	at org.maproulette.controllers.api.TaskController.$anonfun$setTaskStatus$2(TaskController.scala:442)
	at org.maproulette.session.SessionManager.$anonfun$authenticated$2(SessionManager.scala:178)
	at scala.util.Try$.apply(Try.scala:210)
	at org.maproulette.session.SessionManager.$anonfun$authenticated$1(SessionManager.scala:178)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:447)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

The call above was performed on a task that was rejected by reviewer before.

MapRoulette backend v3.8.4

The code that throws was introduced [in this PR](https://github.com/maproulette/maproulette2/pull/726/files). 
I could not find the root cause so far.

@krotstan do you have any ideas from the top of your head?
Thanks in advance!

**Comment by krotstan** [comment]
Are both a reviewer and mapper set on that task? Who is trying to change the status, an admin of the project the challenge belongs to?

**Comment by AntonRutkevich** [comment]
In `tasks` table, `completed_by` column is set to a valid user.
In `task_review` table, `review_requested_by` and `reviewed_by` are both set too.
The user who is trying to change the status is not an admin of the project, it's the mapper. The call is done from the MapRoulette frontend. 

One more thing I noticed, is that both affected tasks were skipped/marked  by another mapper before coming to the one who tried to mark them as Fixed with the call above.

**Comment by mgcuthbert** [comment]
Closed issue, as this has been deployed. If it persists please reopen the issue. Thanks!

**Comment by AntonRutkevich** [comment]
I do confirm that the issue is fixed. Thanks!
